# Header
menu:
  Home: /
  # Delete this row if you don't want categories in your header nav bar
  Categories:
  Résumé: /resume/index.html
  About: /about/index.html

# Content
fancybox: true

# Thumbnail
thumbnail: true

# Scroll Loading
scrollLoading: true

# Sidebar
social_links:
  linkedin: https://www.linkedin.com/in/kenneth-cummins
  google_plus: https://plus.google.com/+KennethCummins
  diaspora: https://pluspora.com/people/3c50c4a0ad6801364692005056268def
  github: https://github.com/kvcummmins
  twitter: https://www.twitter.com/kvcummins
  rss: atom.xml
widgets:
- recent_posts
- category
- archive
- tag
- tagcloud
- links

# Links
links:
  Hexo: http://hexo.io

# Don't Use Google APIs if you are in google-blocked areas
use_google_apis: true

# Miscellaneous
google_analytics: UA-6605488-1
favicon: /favicon.png
fb_admins:
fb_app_id:
